import type { GalleryImage } from './types';

export const IMAGES_PER_PAGE = 6;

// Using placeholder images as the actual images are not available.
// The dimensions are chosen to mimic the comic book/illustration style.
export const ALL_GALLERY_IMAGES: GalleryImage[] = [
  { id: 48, src: '/images/48.png', alt: 'Gallery image 48' },
  { id: 47, src: '/images/47.png', alt: 'Gallery image 47' },
  { id: 46, src: '/images/46.png', alt: 'Gallery image 46' },
  { id: 30, src: '/images/30.png', alt: 'Gallery image 30' },
  { id: 31, src: '/images/31.png', alt: 'Gallery image 31' },
  { id: 32, src: '/images/32.png', alt: 'Gallery image 32' },
  { id: 37, src: '/images/37.png', alt: 'Gallery image 37' },
  { id: 34, src: '/images/34.png', alt: 'Gallery image 34' },
  { id: 42, src: '/images/42.png', alt: 'Gallery image 42' },
  { id: 1, src: '/images/1.png', alt: 'Gallery image 1' },
  { id: 2, src: '/images/2.png', alt: 'Gallery image 2' },
  { id: 4, src: '/images/4.png', alt: 'Gallery image 4' },
  { id: 6, src: '/images/6.png', alt: 'Gallery image 6' },
  { id: 7, src: '/images/7.png', alt: 'Gallery image 7' },
  { id: 8, src: '/images/8.png', alt: 'Gallery image 8' },
  { id: 9, src: '/images/9.png', alt: 'Gallery image 9' },
  { id: 11, src: '/images/11.png', alt: 'Gallery image 11' },
  { id: 12, src: '/images/12.png', alt: 'Gallery image 12' },
  { id: 13, src: '/images/13.png', alt: 'Gallery image 13' },
  { id: 14, src: '/images/14.png', alt: 'Gallery image 14' },
  { id: 15, src: '/images/15.png', alt: 'Gallery image 15' },
  { id: 16, src: '/images/16.png', alt: 'Gallery image 16' },
  { id: 17, src: '/images/17.png', alt: 'Gallery image 17' },
  { id: 18, src: '/images/18.png', alt: 'Gallery image 18' },
  { id: 19, src: '/images/19.png', alt: 'Gallery image 19' },
  { id: 20, src: '/images/20.png', alt: 'Gallery image 20' },
  { id: 21, src: '/images/21.png', alt: 'Gallery image 21' },
  { id: 22, src: '/images/22.png', alt: 'Gallery image 22' },
  { id: 23, src: '/images/23.png', alt: 'Gallery image 23' },
  { id: 24, src: '/images/24.png', alt: 'Gallery image 24' },
  { id: 25, src: '/images/25.png', alt: 'Gallery image 25' },
  { id: 26, src: '/images/26.png', alt: 'Gallery image 26' },
  { id: 27, src: '/images/27.png', alt: 'Gallery image 27' },
  { id: 28, src: '/images/28.png', alt: 'Gallery image 28' },
  { id: 29, src: '/images/29.png', alt: 'Gallery image 29' },
  { id: 38, src: '/images/38.png', alt: 'Gallery image 38' },
  { id: 39, src: '/images/39.png', alt: 'Gallery image 39' },
  { id: 40, src: '/images/40.png', alt: 'Gallery image 40' },
  { id: 41, src: '/images/41.png', alt: 'Gallery image 41' },
  { id: 43, src: '/images/43.png', alt: 'Gallery image 43' },
  { id: 44, src: '/images/44.png', alt: 'Gallery image 44' },
  { id: 45, src: '/images/45.png', alt: 'Gallery image 45' },
  { id: 49, src: '/images/49.png', alt: 'Gallery image 49' },
  { id: 50, src: '/images/50.png', alt: 'Gallery image 50' },
  { id: 52, src: '/images/52.png', alt: 'Gallery image 52' },
];
